name = "OptimalControlProblems"
uuid = "59046045-fb9c-4c23-964f-ff0a25704f96"
authors = ["Olivier Cots <olivier.cots@toulouse-inp.fr>"]
version = "0.2.1"

[deps]
CTBase = "54762871-cc72-4466-b8e8-f6c8b58076cd"
CTModels = "34c4fa32-2049-4079-8329-de33c2a22e2d"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
ExaModels = "1037b233-b668-4ce9-9b63-f9f681f55dd2"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"

[weakdeps]
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
OptimalControl = "5f98b655-cc9a-415a-b60e-744165666948"

[extensions]
JuMPModels = "JuMP"
OptimalControlModels = "OptimalControl"

[compat]
CTBase = "0.16"
CTModels = "0.6"
DocStringExtensions = "0.9"
ExaModels = "0.9"
JuMP = "1"
OptimalControl = "1"
OrderedCollections = "1"
julia = "1.10"
