balanced_field_meta = OrderedDict(
    :grid_size => 200,
    :parameters => (
        t0 = 0.0,
        m = 79015.8,      # mass (kg)
        g = 9.80665,      # gravity (m/s^2)
        ρ = 1.225,        # air density (kg/m^3)
        S = 124.7,        # surface (m^2)
        CD0 = 0.03,       # zero-lift drag coefficient
        AR = 9.45,        # aspect ratio
        e = 0.801,        # Oswald efficiency
        CL0 = 0.5,        # zero-alpha lift coefficient
        CL_max = 2.0,     # max lift coefficient
        h_w = 1.0,        # height of wing above CoG (m)
        span = 35.7,      # wingspan (m)
        α_max = 0.1745,   # alpha at CL_max (10 degrees in rad)
        T = 120102.0,     # thrust (N) - one engine out
        r_t0 = 600.0,     # initial range (m) at V1
        v_t0 = 70.0,      # initial velocity (m/s) at V1
        h_t0 = 0.0,       # initial altitude (m)
        γ_t0 = 0.0,       # initial flight path angle (rad)
        h_tf = 10.668,    # final altitude (35 ft in m)
        γ_tf = 0.0873,    # final flight path angle (5 degrees in rad)
        v_min = 0.0,
        v_max = 100.0,
        α_min = -0.1745,  # -10 degrees
        α_max_ctrl = 0.2618, # 15 degrees
    ),
)
