insurance_meta = OrderedDict(
    :grid_size => 500,
    :state_name => ["I", "m", "x₃"],
    :costate_name => ["∂I", "∂m", "∂x₃"],
    :control_name => ["h", "R", "H", "U", "dUdR"],
    :variable_name => nothing,
    :time_grid_name => Dict(
        :initial_time => "t0", 
        :final_time => "tf", 
        :grid_size => "N"
    ),
    :parameters => (
        t0 = 0, 
        tf = 10,
        γ = 0.2,
        λ = 0.25,
        h0 = 1.5,
        w = 1,
        s = 10,
        k = 0,
        σ = 0,
        α = 4,
        I_l = 0,
        I_u = 1.5,
        m_l = 0,
        m_u = 1.5,
        h_l = 0,
        h_u = 25,
        R_l = 0,
        H_l = 0,
        U_l = 0,
        dUdR_l = 0.001,
        P_l = 0,
        I_t0 = 0,
        m_t0 = 0.001,
        x₃_t0 = 0,
    ),
)
