jackson_meta = OrderedDict(
    :grid_size => 500,
    :state_components => ["a", "b", "x₃"],
    :costate_components => ["∂a", "∂b", "∂x₃"],
    :control_components => ["u"],
    :variable_components => nothing,
    :time_grid_names => Dict(
        :initial_time => "t0", 
        :final_time => "tf", 
        :grid_size => "N",
    ),
    :parameters => (
        t0 = 0,
        tf = 4,
        k1 = 1,
        k2 = 10,
        k3 = 1,
        a_l = 0,
        a_u = 1.1,
        b_l = 0,
        b_u = 1.1,
        x₃_l = 0,
        x₃_u = 1.1,
        u_l = 0,
        u_u = 1,
        a_t0 = 1,
        b_t0 = 0,
        x₃_t0 = 0,
    ),
)
