moonlander_meta = OrderedDict(
    :grid_size => 500,
    :state_components => ["p₁", "p₂", "dp₁", "dp₂", "θ", "dθ"],
    :costate_components => ["∂p₁", "∂p₂", "∂dp₁", "∂dp₂", "∂θ", "∂dθ"],
    :control_components => ["F₁", "F₂"],
    :variable_components => ["tf"],
    :time_grid_names => Dict(
        :initial_time => "t0", 
        :final_time => "tf", 
        :grid_size => "N",
    ),
    :parameters => (
        t0 = 0,
        m = 1,
        g = 9.81,
        I = 0.1,
        D = 1,
        max_thrust = 2*9.81,
        tf_l = 0.1,
        tf_u = 1.0,
        F₁_l = 0,
        F₂_l = 0,
        p₁_t0 = 0,
        p₂_t0 = 0,
        dp₁_t0 = 0,
        dp₂_t0 = 0,
        θ_t0 = 0,
        dθ_t0 = 0,
        p₁_tf = 5,
        p₂_tf = 5,
        dp₁_tf = 0,
        dp₂_tf = 0,
    ),
)
