robot_meta = OrderedDict(
    :grid_size => 250,
    :state_components => ["ρ", "dρ", "θ", "dθ", "ϕ", "dϕ"],
    :costate_components => ["∂ρ", "∂dρ", "∂θ", "∂dθ", "∂ϕ", "∂dϕ"],
    :control_components => ["uρ", "uθ", "uϕ"],
    :variable_components => ["tf"],
    :time_grid_names => Dict(
        :initial_time => "t0", 
        :final_time => "tf", 
        :grid_size => "N",
    ),
    :parameters => (
        t0 = 0,
        L = 5,
        # Lower and upper bounds on the controls,
        uρ_l = -1,
        uρ_u = 1,
        uθ_l = -1,
        uθ_u = 1,
        uϕ_l = -1,
        uϕ_u = 1,
        # Initial positions of the length and the angles for the robot arm,
        ρ_t0 = 4.5,
        θ_t0 = 0,
        ϕ_t0 = π/4,
        dρ_t0 = 0,
        dθ_t0 = 0,
        dϕ_t0 = 0,
        # Final positions
        ρ_tf = 4.5,
        θ_tf = 2π/3,
        ϕ_tf = π/4,
        dρ_tf = 0,
        dθ_tf = 0,
        dϕ_tf = 0,
        #
        ρ_l = 0,
        θ_l = -π,
        θ_u = π,
        ϕ_l = 0,
        ϕ_u = π,
        tf_l = 0.1,
    ),
)
