space_shuttle_meta = OrderedDict(
    :N => 500,
    :state_name => ["scaled_h", "ϕ", "θ", "scaled_v", "γ", "ψ"],
    :costate_name => ["∂h", "∂ϕ", "∂θ", "∂v", "∂γ", "∂ψ"],
    :control_name => ["α", "β"],
    :variable_name => ["tf"],
    :time_grid_name => Dict(
        :initial_time => "t0", 
        :final_time => "tf", 
        :steps_number => "N"
    ),
    :parameters => (
        t0 = 0,
        w = 203000.0,    # weight (lb),
        g₀ = 32.174,     # acceleration (ft/sec^2),
        ## Aerodynamic and atmospheric forces on the vehicle,
        ρ₀ = 0.002378,
        hᵣ = 23800,
        Rₑ = 20902900,
        μ = 0.14076539e17,
        S = 2690,
        a₀ = -0.20704,
        a₁ = 0.029244,
        b₀ = 0.07854,
        b₁ = -0.61592e-2,
        b₂ = 0.621408e-3,
        # ,
        Δt_min = 3.5,
        Δt_max = 4.5,
        ## Initial conditions,
        h_s = 2.6,          # altitude (ft) / 1e5,
        ϕ_s = deg2rad(0),   # longitude (rad),
        θ_s = deg2rad(0),   # latitude (rad),
        v_s = 2.56,         # velocity (ft/sec) / 1e4,
        γ_s = deg2rad(-1),  # flight path angle (rad),
        ψ_s = deg2rad(90),  # azimuth (rad),
        α_s = deg2rad(0),   # angle of attack (rad),
        β_s = deg2rad(0),   # bank angle (rad),
        t_s = 1.00,         # time step (sec),
        ## Final conditions, the so-called Terminal Area Energy Management (TAEM),
        h_t = 0.8,          # altitude (ft) / 1e5,
        v_t = 0.25,         # velocity (ft/sec) / 1e4,
        γ_t = deg2rad(-5),  # flight path angle (rad),
    ),
)
