steering_meta = OrderedDict(
    :grid_size => 500,
    :state_components => ["x₁", "x₂", "x₃", "x₄"],
    :costate_components => ["∂x₁", "∂x₂", "∂x₃", "∂x₄"],
    :control_components => ["u"],
    :variable_components => ["tf"],
    :time_grid_names => Dict(
        :initial_time => "t0", 
        :final_time => "tf", 
        :grid_size => "N",
    ),
    :parameters => (
        t0 = 0,
        a = 100,
        u_min = -π/2,
        u_max = π/2,
        tf_l = 0,
        x₁_t0 = 0,
        x₂_t0 = 0,
        x₃_t0 = 0,
        x₄_t0 = 0,
        x₂_tf = 5,
        x₃_tf = 45,
        x₄_tf = 0,
    ),
)
